version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566-4583:4566-4583
    container_name: square-number-lambda-localstack
    environment:
      - SERVICES=serverless
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

